name       : zim-tools
version    : 3.1.3
release    : 4
source     :
    - https://github.com/openzim/zim-tools/archive/refs/tags/3.1.3.tar.gz : e15d1a15a9cf1347858a260d60cb52a32e56878ffcf4f953ac927caeb6a3ee67
    - https://raw.githubusercontent.com/kainjow/Mustache/v4.1/mustache.hpp : 6a07bd8c31be6bb3eae6df98b12f89df8931604bd890e8bba59298a68b89ff29
license    : GPL-3.0-only
component  : office.viewers
summary    : Various ZIM command line tools
description: |
    Most famous tools are: zimcheck verifies that a given ZIM file is not corrupted. It provides many features to secure that ZIM entries are proper and properly linked. zimdump inspects or dumps (part of) a ZIM file. zimwriterfs creates ZIM files from a locally-stored directory containing "self-sufficient" HTML content (with pictures, javascript and stylesheets). The result will contain all the files of the local directory compressed and merged in the ZIM file. Nothing more, nothing less. The generated file can be opened with a ZIM reader; Kiwix is one example, but there are others. A few other tools are provided as well but are of less value for most of the usages.
builddeps  :
    - pkgconfig(docopt)
    - pkgconfig(gumbo)
    - pkgconfig(icu-io)
    - pkgconfig(libmagic)
    - pkgconfig(libzim)
    - pkgconfig(zlib)
environment: CXXFLAGS="${CXXFLAGS} -I$workdir/include"
setup      : |
    mkdir -p $workdir/include
    cp $sources/mustache.hpp $workdir/include/
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
